# Generated by Django 3.1.14 on 2022-09-24 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('lugar', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='autor',
            field=models.ManyToManyField(to='personal.Persona'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='congreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicaciones.congreso'),
        ),
    ]
